### PR TITLE
Replace prettier config with more general EditorConfig

### LINKED ISSUE #215: Replace prettier config with more general EditorConfig
Improves development in vscode
https://editorconfig.org/

### PR DESCRIPTION
**Pull request by clemens-mw**
# Replace prettier config with more general EditorConfig

Closes #215

## Description

See https://editorconfig.org/ and https://prettier.io/docs/en/configuration.html#editorconfig

## Definition of Done

A PR is only ready for merge once all the following acceptance criteria are fulfilled:
* [x]  All TODOs related to this PR have been closed
* [x]  There are automated tests for newly written code and bug fixes
* [x]  All bugs discovered while working on this PR have been submitted as issues (if not already an open issue)
* [x]  Documentation ([README.md](https://github.com/MaibornWolff/metric-gardener/blob/main/README.md), [UPDATE_GRAMMARS.md](https://github.com/MaibornWolff/metric-gardener/blob/main/UPDATE_GRAMMARS.md)) has been updated

### CODE REVIEW

**Comment by ResistantBear** [comment]
As far as I understand, this defines some code style rules? We already have this formatter called "prettier" which runs as commit hook with every commit and is also included in the CI pipeline to ensure that the code is formatted in the way "prettier" wants it. You can also run it via `npm run format`.

There also seems to be a Prettier addon for VS Code. 

I don't know/haven't tested if this is useful nevertheless or produces conflicts with prettier when using VS Code or IntelliJ Ultimate.

**Comment by clemens-mw** [comment]
Yes, prettier works perfectly in VS Code, but there are some options in EditorConfig, that prettier doesn't have:
 - charset
 - insert final newline
 - trim trailing whitespace

EditorConfig helps that these options are configured everywhere the same.

This is also integrated with prettier: 
https://prettier.io/docs/en/configuration.html#editorconfig

**Comment by clemens-mw** [comment]
but i forgot to change the prettier configuration, will do now

**Review by ResistantBear — APPROVED** [review]
LGTM

**Pull request merged**
